# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='waterID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
