# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0002_document_waterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterinfo',
            name='imageURL',
            field=models.CharField(blank=True, default=b'', max_length=80),
        ),
    ]
