# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0005_profile_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterinfo',
            name='filtered',
            field=models.CharField(default=b'U', max_length=8),
        ),
    ]
