# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0006_waterinfo_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
