# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0007_auto_20170320_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farm',
            field=models.CharField(default=b'U', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='tankAge',
            field=models.CharField(default=b'U', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='tankEmpty',
            field=models.CharField(default=b'U', max_length=8),
        ),
        migrations.AddField(
            model_name='waterinfo',
            name='farm',
            field=models.CharField(default=b'U', max_length=8),
        ),
        migrations.AddField(
            model_name='waterinfo',
            name='tankAge',
            field=models.CharField(default=b'U', max_length=8),
        ),
        migrations.AddField(
            model_name='waterinfo',
            name='tankEmpty',
            field=models.CharField(default=b'U', max_length=8),
        ),
    ]
