# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0008_auto_20170411_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterinfo',
            name='fertilizer',
            field=models.CharField(default=b'U', max_length=8),
        ),
    ]
