# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0009_waterinfo_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pet',
            field=models.CharField(default=b'No', max_length=8),
        ),
        migrations.AddField(
            model_name='waterinfo',
            name='pet',
            field=models.CharField(default=b'No', max_length=8),
        ),
    ]
