# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-30 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws', '0010_auto_20170413_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterinfo',
            name='school',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
    ]
